### ISSUE TITLE
Create Kubevirt DataVolume Images

### ISSUE THREAD

**Issue by aamoyel** [didactiklabs/infra#22]

**Comment by aamoyel** [comment]
If you want to clone a PV created by a DataVolume across namespaces, you need to write RBACs for our VMs. Here you can find a exemple to clone PVs from default to aamoyel namespace :
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdi-cloner
rules:
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aam-cdi-cloner
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: aamoyel
roleRef:
  kind: ClusterRole
  name: cdi-cloner
  apiGroup: rbac.authorization.k8s.io
```
